### ISSUE TITLE
Fix Google Analytics tracking for Sahara Reporters Health

### ISSUE THREAD

**Issue by StephenAbbott** [CodeForAfrica/HealthTools#13]
The Google Analytics tracking code being used on http://health.saharareporters.com doesn't look to be recording any analytics in the dashboard I can see in the Code for Africa GA account.

Please check and fix the tracking code.

**Comment by nickhargreaves** [comment]
Misspelled the domain name on the GA account. Should work now.

**Comment by StephenAbbott** [comment]
Hmmmm. Still can't see any data coming through on the GA dashboard. Have you pushed the changes live now?

**Comment by nickhargreaves** [comment]
Hey @StephenAbbott , found a different problem. But now I've confirmed that it works properly. Use this repo for Sahara Reporters Health issues https://github.com/codefornigeria/HealthTools

**Comment by StephenAbbott** [comment]
Thanks @nickhargreaves
